using System;

public class Assett
{
    public string SRC_SYSTEM { get; set; }
    public string RUN_ID { get; set; }
    public int ROW_ID { get; set; }
    public string BILLINGFREQUENCY__C { get; set; }
    public bool ISDISCONNECTABLE__C { get; set; }
    public string NE__STATUS__C { get; set; }
    public int CONTRACTTYPE__C { get; set; }
    public double ANNUALCONSUMPTION__C { get; set; }
    public long DISTRIBUTORVAT__C { get; set; }
    public string NE__STARTDATE__C { get; set; }
    public string NE__ENDDATE__C { get; set; }
    public string MARKETTYPE__C { get; set; }
    public string ZAPPKEYCONTRACT__C { get; set; }
    public string COMMODITY_TYPE__C { get; set; }
    public int INVOICEJOINTTYPE__C { get; set; }
    public int VATRATE__C { get; set; }
    public string CHANNEL__C { get; set; }
    public string NE__PRODID__C { get; set; }
    public string NAME { get; set; }
    public string PRODUCTDESCRIPTION__C { get; set; }
    public string PRICE_LIST_CODE_D__C { get; set; }
    public string PROCESS__C { get; set; }
    public string DESCRIPTION { get; set; }
    public string OWNERID { get; set; }
    public string QUOTEENDDATE__C { get; set; }
    public string DEADLINEFORWITHDRAWAL__C { get; set; }
    public string ACCOUNTID { get; set; }
    public string NE__BILLINGPROF__C { get; set; }
    public string NE__SERVICE_POINT__C { get; set; }
    public string SUBSCRIBER__C { get; set; }
    public string GROUPCODE__C { get; set; }
    public string GROUPLEADERCODE__C { get; set; }
    public string NE__ORDER_CONFIG__C { get; set; }
    public string TREATMENT__C { get; set; }
    public string USAGE_CATEGORY__C { get; set; }
    public string USAGETYPE__C { get; set; }
    public int ANNUALCONSUMPTIONSMCYEAR__C { get; set; }
    public string EXCISEDUTIESELE__C { get; set; }
    public string EXCISEDUTIESGAS__C { get; set; }
    public string EXCISEDUTIESFIXED__C { get; set; }
    public int EXCISEDUTIESPERCENTAGE__C { get; set; }
    public string EXCISEDUTIESGAS1__C { get; set; }
    public int EXCISEDUTIESGAS1PERCENT__C { get; set; }
    public string EXCISEDUTIESGAS2__C { get; set; }
    public int EXCISEDUTIESGAS2PERCENT__C { get; set; }
    public string DIVISION__C { get; set; }
    public string PODPDRPDC__C { get; set; }
    public string ASSETCITY__C { get; set; }
    public string ASSETCOUNTRY__C { get; set; }
    public string ASSETSTREETNUMBER__C { get; set; }
    public int ASSETZIPCODE__C { get; set; }
    public string ASSETPROVINCE__C { get; set; }
    public string ASSETSTREET__C { get; set; }
    public string ASSETTOPONYMY__C { get; set; }
    public int ASSETISTAT__C { get; set; }
    public bool ISRESIDENTATSUPPLY__C { get; set; }
    public string SOURCE__C { get; set; }
    public string ORIGIN__C { get; set; }
    public string BRANCH__C { get; set; }
    public string WEBREQUESTCODE__C { get; set; }
    public string FINALCUSTOMERNAME__C { get; set; }
    public string FINALCUSTOMERCFVAT__C { get; set; }
    public string FINALCUSTOMEREMAIL__C { get; set; }
    public string FINALCUSTOMERPHONE__C { get; set; }
    public string NE__ACTIVATION_DATE__C { get; set; }
    public string NE__ASSETITEMENTERPRISEID__C { get; set; }
    public int EXCISEDUTIES_DATE { get; set; }
    public string ZAPPPARENTCA__C { get; set; }
    public string ZAPPCA__C { get; set; }
    public string ZAPPLOTCODE__C { get; set; }
    public string CUP__C { get; set; }
    public string CIG__C { get; set; }
    public string CIGCHILD__C { get; set; }
    public string ASSETCODE__C { get; set; }
    public string BILLINGPROFILECODE__C { get; set; }
    public string CUSTOMERCODE__C { get; set; }
    public string SERVICEPOINTCODE__C { get; set; }
    public string PRICELIST__C { get; set; }
}
