using System;

public class ServicePoint
{
    public string SRC_SYSTEM { get; set; }
    public string RUN_ID { get; set; }
    public int ROW_ID { get; set; }
    public string NE__CITY__C { get; set; }
    public string CITYDE__C { get; set; }
    public string NE__COUNTRY__C { get; set; }
    public string COUNTRYDE__C { get; set; }
    public string NE_STREET_NUMBER__C { get; set; }
    public string ASSETSHIPTO__C { get; set; }
    public int NE__POSTAL_CODE__C { get; set; }
    public string NE__PROVINCE__C { get; set; }
    public string NE__STREET__C { get; set; }
    public string NE_STREETDE__C { get; set; }
    public string Z_ACC_TOPONIMY_TEXT__C { get; set; }
    public int ASSETISTAT__C { get; set; }
    public string SUPPLYSTAIRCASE__C { get; set; }
    public string SUPPLYFLATNUMBER__C { get; set; }
    public string SUPPLYFLOOR__C { get; set; }
    public string NE__TYPE__C { get; set; }
    public string CUSTOMERTYPE__C { get; set; }
    public int VOLTAGE__C { get; set; }
    public double AVAILABLEPOWER__C { get; set; }
    public string APPLIEDPOWER__C { get; set; }
    public double ENGRAVEDPOWER__C { get; set; }
    public string VOLTAGELEVEL__C { get; set; }
    public bool ISRESIDENTATSUPPLY__C { get; set; }
    public int ANNUALCONSUMPTION__C { get; set; }
    public bool ISLIMITEDMETER__C { get; set; }
    public bool ISENERGYINTENSIVE__C { get; set; }
    public bool ISAUXILIARYPOINT__C { get; set; }
    public bool ISTD1__C { get; set; }
    public bool ISMETER2G__C { get; set; }
    public int METERACTIVATIONDATE2G__C { get; set; }
    public string ENERGYINTENSIVECLASS__C { get; set; }
    public string ZAPPKEYPLANT__C { get; set; }
    public string POD__C { get; set; }
    public string PDR__C { get; set; }
    public string DISTRIBUTOR__C { get; set; }
    public long DISTRIBUTORVAT__C { get; set; }
    public string REGISTRATIONNUMBER__C { get; set; }
    public string NE__ACCOUNT__C { get; set; }
    public string PLANTTYPE__C { get; set; }
    public string RENEWABLE__C { get; set; }
    public string PROGRAMMABLE__C { get; set; }
    public int INSTALLEDCAPACITY__C { get; set; }
    public int PRODUCTION__C { get; set; }
    public string Z_ACC_CARRIER__C { get; set; }
    public string Z_ACC_COMPANY_CODE__C { get; set; }
    public string Z_ACC_REMIT_CODE__C { get; set; }
    public string Z_ACC_COST_CENTER__C { get; set; }
    public string Z_ACC_COST_CENTER_DESCRIPTION__C { get; set; }
    public int DECLARATIONDATE__C { get; set; }
    public int VALIDFROM__C { get; set; }
    public int VALIDTO__C { get; set; }
    public string HOLDERSTATUS__C { get; set; }
    public string BUILDINGTYPE__C { get; set; }
    public string CADASTRALCITY__C { get; set; }
    public string CADASTRALPROVINCE__C { get; set; }
    public int? CADASTRALCODE__C { get; set; }
    public string URBANSECTION__C { get; set; }
    public int? SHEET__C { get; set; }
    public int? SUBORDINATE__C { get; set; }
    public int? PARCEL__C { get; set; }
    public int? PARCELEXTENSION__C { get; set; }
    public string PARCELTYPE__C { get; set; }
    public string ENROLLMENTLEVEL__C { get; set; }
    public string PROPERTYUSAGE__C { get; set; }
    public string USAGECATEGORY__C { get; set; }
    public string CLASSGASSAMPLING__C { get; set; }
    public string REMI__C { get; set; }
    public string CLASSCOUNTER__C { get; set; }
    public int ANNUALCONSUMPTIONSMCYEAR__C { get; set; }
    public string EXCISEELE__C { get; set; }
    public string EXCISEDUTIESGAS__C { get; set; }
    public int EXCISEDUTIESPERCENTAGE__C { get; set; }
    public string EXCISEDUTIESFIXED__C { get; set; }
    public string EXCISEDUTIESGAS1__C { get; set; }
    public int EXCISEDUTIESGAS1PERCENT__C { get; set; }
    public string EXCISEDUTIESGAS2__C { get; set; }
    public int EXCISEDUTIESGAS2PERCENT__C { get; set; }
    public string CGSMCDAY__C { get; set; }
    public string CGCALCFORREMI__C { get; set; }
    public string BILLINGFREQUENCY__C { get; set; }
    public int INVOICEJOINTTYPE__C { get; set; }
    public int CONTRACTTYPE__C { get; set; }
    public string ACTIVEADDRESSLANGUAGE__C { get; set; }
    public string USAGETYPE__C { get; set; }
    public string HOLDINGTYPE__C { get; set; }
    public int EXCISEDUTIES_DATE { get; set; }
    public string CUSTOMERCODE__C { get; set; }
    public string SERVICEPOINTCODE__C { get; set; }
    public string PHASE__C { get; set; }
    public string SYSTECHSTATUS__C { get; set; }
}