using System;

public class Account
    {
        public string SRC_SYSTEM { get; set; }
        public string RUN_ID { get; set; }
        public int ROW_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string NAME { get; set; }
        public string Z_ACC_LEGAL_FORM__C { get; set; }
        public string BILLINGCITY { get; set; }
        public string BILLINGCITYDE__C { get; set; }
        public string BILLINGCOUNTRY { get; set; }
        public string BILLINGCOUNTRYDE__C { get; set; }
        public string BILLINGSTREETNUMBER__C { get; set; }
        public int BILLINGPOSTALCODE { get; set; }
        public string BILLINGSTATE { get; set; }
        public string BILLINGSTREET { get; set; }
        public string BILLINGSTREETDE__C { get; set; }
        public string BILLINGTOPONYMY__C { get; set; }
        public int BILLINGISTAT__C { get; set; }
        public string BILLINGFLATNUMBER__C { get; set; }
        public string ZAPPKEYBUSINESSPARTNER__C { get; set; }
        public string DIVISION__C { get; set; }
        public string CUSTOMERTYPE__C { get; set; }
        public string NE__FISCAL_CODE__C { get; set; }
        public int? NE__VAT__C { get; set; }
        public string RETURNMARKET__C { get; set; }
        public int? PHONE { get; set; }
        public string PHONEBUSINESS__C { get; set; }
        public string PERSONMOBILEPHONE { get; set; }
        public string MOBILEBUSINESS__C { get; set; }
        public string FAX { get; set; }
        public string Z_ACC_PEC__C { get; set; }
        public string AGENCY__C { get; set; }
        public int AGENCYASSIGNMENTDATE__C { get; set; }
        public string CONTACTHOURS__C { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ISNOTLOWVOLTAGEPOINT__C { get; set; }
        public bool ISNOTSMALLBUSINESS__C { get; set; }
        public string NE__STATUS__C { get; set; }
        public string PARENTID { get; set; }
        public string Z_ACC_APPROVAL_STATE__C { get; set; }
        public string Z_ACC_ATECO_CODE__C { get; set; }
        public string Z_ACC_CODICE_CRM__C { get; set; }
        public string Z_ACC_CODICE_RESELLER__C { get; set; }
        public int Z_ACC_CODICE_SDI__C { get; set; }
        public string Z_ACC_DESCRIZIONE_CODICE_ATECO__C { get; set; }
        public string Z_ACC_PEC_SDI__C { get; set; }
        public string PREDEREDCONTACTCHANNEL__C { get; set; }
        public string Z_ACC_STATO_ATTIVITA__C { get; set; }
        public string NE__E_MAIL__C { get; set; }
        public string INVOICEMAILADDRESS__C { get; set; }
        public string OWNERID { get; set; }
        public string VATGROUP__C { get; set; }
        public int VATGROUPSTARTDATE__C { get; set; }
        public int VATGROUPENDDATE__C { get; set; }
        public string PREFERREDLANGUAGE__C { get; set; }
        public string SUBJECTSUBTYPE__C { get; set; }
        public bool ISDUPLICATED__C { get; set; }
        public string CUSTOMERCODE__C { get; set; }
        public string MARKETTYPE__PC { get; set; }
        public string REGIMESPLITPAYMENT__C { get; set; }
        public string CUSTOMERSEGMENTTYPE__C { get; set; }
}
